# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: sudo apt-get update
  displayName: 'updatenew'

- script: sudo apt-get install "libboost-all-dev" -y
  displayName: 'packageinstaller'
- script: echo "BuildNumber:$(Build.BuildNumber)" > readme.txt
          #echo "BUILD NUMBER: $Build.BuildNumber" >> readme.txt
                #echo Add other tasks to build, test, and deploy your project.
                  #echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- powershell: gci env:* | sort-object name | Format-Table -AutoSize | Out-File $env:BUILD_ARTIFACTSTAGINGDIRECTORY/environment-variables.txt

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'
